const tintColorLight = '#2f95dc'
const tintColorDark = '#fff'
export default {
  light: {
    text: '#000',
    background: '#fff',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    primary: '#5E72E4',
    secondary: '#11CDEF',
    placeholder: '#ADB5BD',
    main_font: '#525F7F',
    success: '#2DCE89',
    black: '#212529',
    danger: '#F5365C',
    blackOpacity: 'rgba(0,0,0, 0.4)',
    blackOpacityDarker: 'rgba(0,0,0, 0.7)',
    purple: '#6c45e2',
    purple_secondary: '#F4F0FF',
    yellow: '#f6ca70',
    yellow_secondary: '#fffaee',
    red: '#ff3e30',
    red_secondary: '#fef1ef',
    dark: '#0c0c0c',
    medium: '#8c8c8c',
    mediumLight: '#d4d4d4',
    light: '#f5f5f5',
    white: '#ffffff'
  },
  dark: {
    text: '#000',
    background: '#fff',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    primary: '#5E72E4',
    secondary: '#11CDEF',
    placeholder: '#ADB5BD',
    main_font: '#525F7F',
    success: '#2DCE89',
    black: '#212529',
    danger: '#F5365C',
    blackOpacity: 'rgba(0,0,0, 0.4)',
    blackOpacityDarker: 'rgba(0,0,0, 0.7)',
    purple: '#6c45e2',
    purple_secondary: '#F4F0FF',
    yellow: '#f6ca70',
    yellow_secondary: '#fffaee',
    red: '#ff3e30',
    red_secondary: '#fef1ef',
    dark: '#0c0c0c',
    medium: '#8c8c8c',
    mediumLight: '#d4d4d4',
    light: '#f5f5f5',
    white: '#ffffff'
  }
}
